POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3Q0IiwiaWQiOiI1ZDI3OGY5NGExOWQ0MzE4OGU4M2JmOWEiLCJpYXQiOjE1NjM0MzgxOTd9.41X0TWrND61YbLejX32TZ7Zx1gDqCa3lj3VO1PTYdTQ

{
  "title": "Test1",
  "author": "Olli Rautiainen",
  "url": "www.test1.com",
  "likes": 100
}